INSERT INTO tb_user (name, email, password) VALUES ('Ana Green', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');
INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Ficção Científica');
INSERT INTO tb_genre (name) VALUES ('Romance');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Mistério');
INSERT INTO tb_genre (name) VALUES ('Ação');

INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Invasão Zumbi', null, 2016, 'https://br.web.img3.acsta.net/pictures/16/10/06/23/09/515438.jpg', 'A Coreia do Sul decreta estado de emergência após um vírus desconhecido tomar conta do país. Algumas pessoas tentam fugir de zumbis e ficam presas em um trem-bala que está a caminho de Busan, a única cidade que não foi afetada pelo vírus.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Parasita', null, 2019, 'https://br.web.img3.acsta.net/c_310_420/pictures/19/10/04/19/58/1046648.jpg', 'Toda a família de Ki-taek está desempregada, vivendo em um porão sujo e apertado, mas uma obra do acaso faz com que ele comece a dar aulas de inglês a uma garota de família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe e filhos bolam um plano para se infiltrarem também na família burguesa, um a um. No entanto, os segredos e mentiras necessários à ascensão social custam caro a todos.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Hospedeiro', null, 2006, 'https://br.web.img2.acsta.net/c_310_420/medias/nmedia/18/87/81/22/19961797.jpg', 'Na beira do rio Han moram Hie-bong e sua família, donos de uma barraca de comida no parque. Seu filho mais velho, Kang-du, tem 40 anos, mas é um tanto imaturo. A filha do meio é arqueira do time olímpico coreano e o filho mais novo está desempregado. Todos cuidam da menina Hyun-seo,', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Okja', null, 2017, 'https://br.web.img3.acsta.net/c_310_420/pictures/17/05/18/16/54/145643.jpg', 'Um imenso animal e a menina que o criou se veem no fogo cruzado entre o ativismo animal, a ganância empresarial e a ética.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('A Chamada', null, 2020, 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b7/Call_poster.jpg/220px-Call_poster.jpg', 'Em 2019, Kim Seo-yeon, de 28 anos, perde seu celular enquanto viaja para visitar sua mãe doente e distante em uma área rural. Chegando em sua casa de infância decadente, ela encontra um telefone sem fio de décadas, e através dele recebe ligações de uma mulher angustiada que diz estar sendo torturada por sua mãe.', 5);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Nova Ordem Espacial', null, 2021, 'https://br.web.img3.acsta.net/c_310_420/pictures/21/01/06/15/33/2468389.jpg', 'Em 2092, quatro rebeldes em busca de sonhos e lixo espacial encontram segredos explosivos ao tentar vender uma humanoide.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Mistério das Garotas Perdidas', null, 2019, 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/Svaha_-_poster.jpg/220px-Svaha_-_poster.jpg', 'Um pastor que pesquisa seitas religiosas pede a ajuda de seu amigo, um monge budista, para investigar um grupo novo com origens misteriosas.', 5);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('#Alive', null, 2020, 'https://br.web.img2.acsta.net/c_310_420/pictures/20/05/27/08/29/4788868.jpg', 'Um vírus terrível destrói a cidade, e um homem se tranca no apartamento para sobreviver. Desconectado do mundo, ele tenta desesperadamente encontrar uma saída.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Sintonizada em Você', null, 2019, 'https://media.fstatic.com/aOVu54D9eVsojfM2ukyDAaqoPLE=/210x312/smart/media/movies/covers/2019/07/fullsizephoto1082431.jpg', 'Durante os anos 1990, Mi Soo e Hyun Woo se conhecem em uma padaria e se apaixonam enquanto compartilham histórias. Porém, o tempo e as oportunidades parecem fazer de tudo para separá-los.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Pandora', null, 2016, 'https://upload.wikimedia.org/wikipedia/en/b/ba/Pandora_-_%ED%8C%90%EB%8F%84%EB%9D%BC.jpg?20170411220508', 'Um homem arrisca a própria vida para salvar seu país de um desastre iminente quando um terremoto atinge um vilarejo onde existe uma usina nuclear.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Homem de Lugar Nenhum', null, 2010, 'https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/82/67/27/19631186.jpg', 'A única ligação que o ex-agente Cha Tae-shik (Bin Won) tem com o resto do mundo é uma menina, Jeong So-mi (Sae-ron Kim), que vive nas proximidades. Sua mãe, Hyo-jeong (Hyo-seo Kim), que é contrabandista de drogas numa organização, confia a Tae-shik todo seu produto, mas sem que ele saiba o que é.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Lamento', null, 2016, 'https://upload.wikimedia.org/wikipedia/pt/thumb/5/56/Gokseong.jpg/240px-Gokseong.jpg', 'A chegada de um estranho misterioso em uma aldeia tranquila coincide com uma onda de assassinatos cruéis, causando pânico e desconfiança entre os moradores. Enquanto investiga o suspeito, policial percebe que sua filha pode ter sido vítima do ataque.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Expresso do Amanhã', null, 2013, 'https://upload.wikimedia.org/wikipedia/pt/thumb/d/de/Snowpiercer.jpg/200px-Snowpiercer.jpg', 'Os únicos sobreviventes de uma fracassada tentativa de conter o aquecimento global são obrigados a viver em um trem separados em vagões que determinam sua condição social.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Em Chamas', null, 2016, 'https://upload.wikimedia.org/wikipedia/pt/thumb/1/1e/Burning_2018.png/200px-Burning_2018.png', 'Durante um dia normal de trabalho como entregador, Jong-soo reencontra Hae-mi, uma antiga amiga que vivia no mesmo bairro que ele. A jovem está com uma viagem marcada para o exterior e pede para Jong-soo cuidar de seu gato de estimação enquanto ela está longe. Hae-mi volta para casa na companhia de Ben, um jovem misterioso que conheceu na África. No entanto, o forasteiro tem um hobby peculiar, que está prestes a ser revelado aos amigos.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Psychokinesis', null, 2018, 'https://br.web.img3.acsta.net/c_310_420/pictures/17/12/17/21/01/3892098.jpg', 'Ao adquirir superpoderes, um homem embarca em uma jornada para ajudar sua filha e as pessoas ao seu redor, mas descobre que a vida de super-herói não é fácil.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Alerta Vermelho', null, 2019, 'https://br.web.img2.acsta.net/c_310_420/pictures/19/12/18/08/39/5266683.jpg', 'Estagnado desde 1903, a 9 mil pés de altitude, um vulcão entra em erupção na Montanha Baekdu, localizada na fronteira entre a China e a Coréia do Norte. Armada para a ameaça de erupções iminentes, uma equipe de profissionais treinados exclusivamente pela Coréia do Sul e do Norte se une pela primeira vez para uma missão inédita. Juntos, devem unir forças e tentar evitar um desastre catastrófico que ameaça a Península Coreana.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('High Society', null, 2018, 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/High_Society_%282018_film%29.jpg/220px-High_Society_%282018_film%29.jpg', 'Uma ambiciosa curadora de arte e seu marido, um professor de economia com pretensões políticas, vão fazer qualquer coisa para ascender socialmente.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Sweet & Sour', null, 2021, 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Sweet_%26_Sour.jpg/220px-Sweet_%26_Sour.jpg', 'Diante das oportunidades e desafios do mundo real, um casal passa pelos altos e baixos de um relacionamento à distância.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Invasão Zumbi 2', 'Península', 2020, 'https://br.web.img3.acsta.net/c_310_420/pictures/20/02/28/16/31/0418843.jpg', 'Quatro anos após o surto de zumbis que atingiu os passageiros de um trem-bala com destino a Busan, a península coreana ficou devastada. Jung-seok, um ex-soldado que conseguiu fugir do país tem a missão de retornar e surpreendentemente encontra alguns sobreviventes.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Along with the Gods', 'The Two Worlds', 2017, 'https://br.web.img3.acsta.net/c_310_420/pictures/17/11/09/01/34/3738526.jpg', ' Depois de uma morte totalmente inesperada, o bombeiro Ja-hong (Tae-Hyun Cha) é carregado para o além por três guardiões sobrenaturais. É só depois de passar por sete testes de 49 dias que ele ganha a possibilidade da reencarnação. Seus três companheiros permanecem ao seu lado o tempo todo para que possam testemunhar durante seu julgamento.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Noite no Paraíso', null, 2020, 'https://br.web.img3.acsta.net/c_310_420/pictures/21/11/04/22/25/2494167.jpg', 'Escondido em uma ilha após uma tragédia, um gângster injustiçado se envolve com uma mulher que tem seus próprios demônios.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Mimic - Não Confie nas Vozes', null, 2017, 'https://br.web.img3.acsta.net/c_310_420/pictures/18/05/08/01/12/4452591.jpg', 'Uma família se envolve com uma misteriosa criatura conhecida como "Jangsanbum". Ela é capaz de imitar a voz de um ser humano e seduzir as crianças até comê-las.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('As Faces do Demônio', null, 2019, 'https://br.web.img2.acsta.net/c_310_420/pictures/20/10/02/17/51/5263925.jpg', 'Demônio adquire a forma humana e invade a vida de uma família. Um tio, que também é pastor, precisa encarar o trauma de um exorcismo fracassado para salvar a todos.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Sonhos Lúcidos', null, 2017, 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Lucid_Dream_%28%EB%A3%A8%EC%8B%9C%EB%93%9C_%EB%93%9C%EB%A6%BC%29.jpg/220px-Lucid_Dream_%28%EB%A3%A8%EC%8B%9C%EB%93%9C_%EB%93%9C%EB%A6%BC%29.jpg', 'Dae-ho é um jovem jornalista investigativo e pai solteiro que fez alguns inimigos ao expor vários políticos e empresários corruptos. Um dia, seu filho é sequestrado, mas nenhum resgate é exigido. Dae-ho está convencido de que é um ato de vingança de um de seus inimigos que ele expôs. ', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('No Dia do Seu Casamento', null, 2018, 'https://br.web.img2.acsta.net/c_310_420/pictures/22/01/31/18/00/1786077.jpg', 'Hwang Woo-yeon recebe um convite para o casamento de Hwan Seung-hee, seu primeiro amor. Nesse momento, ele começa a relembrar momentos bons e ruins da dupla que os transformaram no que são hoje.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Em Silêncio', null, 2011, 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/The_Crucible-poster.jpg/220px-The_Crucible-poster.jpg', 'Gang In-ho descobre casos de abuso sexual e físico em uma escola para crianças com deficiência auditiva. Com a ajuda de um ativista de direitos humanos, Gang luta contra a comunidade para expor o abuso e acabar com ele.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Armário', null, 2020, 'https://br.web.img3.acsta.net/c_310_420/pictures/22/02/07/17/23/0210277.png', 'Após a morte da esposa, Sang-won e a filha se mudam para uma nova casa. Quando a menina desaparece misteriosamente, ele percebe que um armário da residência esconde segredos macabros.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Amor com Fetiche', null, 2022, 'https://br.web.img2.acsta.net/c_310_420/pictures/22/01/19/17/00/5182594.jpg', 'O amor é um sofrimento gostoso para dois colegas de trabalho que concordam em viver uma relação cheia de jogos, dor e prazer.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Illang', 'A Brigada do Lobo', 2018, 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Illang_The_Wolf_Brigade.jpg/220px-Illang_The_Wolf_Brigade.jpg', 'Em 2029, o esquadrão de elite da polícia Illang combate um grupo terrorista que luta contra a reunificação das duas Coreias. Mas outro inimigo pode estar à espreita.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Tempo de Caça', null, 2020, 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Time_to_Hunt_%28film%29.jpg/220px-Time_to_Hunt_%28film%29.jpg', 'Tempo de Caça acompanha três jovens que decidem roubar para conseguir sobreviver e fugir de uma Córeia do Sul assolada por uma crise financeira. Entretanto, eles não contavam que acabariam chamando a atenção de um assassino impiedoso.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Revenger', null, 2018, 'https://upload.wikimedia.org/wikipedia/en/9/94/Revenger_%282018%29.jpg?20181101180904', 'Situado em um futuro próximo, criminosos perigosos estão alojados em uma ilha-prisão infernal. Um homem se envia propositalmente à ilha para vingar o assassinato de sua família.', 6);


INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Não entendi o filme', 1, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Assisitr pela segunda vez, agora ta fazendo sentindo', 1, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Maravilho', 2, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Filme muito bom', 3, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Legal', 4, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Maravilho', 5, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Filme muito bom', 6, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Legal', 7, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Maravilho', 8, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Filme muito bom', 9, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Legal', 10, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Maravilho', 11, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Filme muito bom', 12, 1);
